# Generated by Django 4.2.5 on 2023-09-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address',
            new_name='postalCode',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='pinCode',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shippingPrice',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='street',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
