# Generated by Django 4.2.5 on 2023-09-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename__id_shippingaddress_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='itemsPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
