# Generated by Django 4.2.5 on 2023-09-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_shippingaddress_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='id',
            new_name='_id',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='street',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shippingPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
