# Generated by Django 4.2.5 on 2023-09-29 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_shippingaddress_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='street',
        ),
    ]
