# Generated by Django 4.2.5 on 2023-09-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_shippingaddress_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
