# Generated by Django 4.2.5 on 2023-10-01 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_shippingaddress_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shippingPrice',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='street',
        ),
    ]
