# Generated by Django 4.2.5 on 2023-10-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_shippingaddress_shippingprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='isPaid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='itemsPrice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paidAt',
        ),
    ]
